import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderPN from "@/components/page/header/page";
import FooterPN from "@/components/page/footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <HeaderPN />{children}
        <FooterPN />
      </body>
    </html>
  );
}
